title: Ryan Warsaw
email: me@ryanwarsaw.com
description: >- 
  Ryan Warsaw is a Software Engineer with a passion for full stack product 
  development and open source practices. His work is primarily oriented around
  the education space.
baseurl: "" 
url: "https://ryanwarsaw.com" 
twitter_username: ryanwarsaw
github_username:  ryanwarsaw

# Build settings
markdown: kramdown
theme: plainwhite
plugins:
  - jekyll-feed

plainwhite:
  name: Ryan Warsaw
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  social_links:
    twitter: ryanwarsaw
    github: ryanwarsaw
    linkedIn: in/ryanwarsaw
