title: Ryan Warsaw
email: me@ryanwarsaw.com
description: >- 
  Ryan Warsaw is a Software Engineer with a passion for full stack product 
  development and open source practices. His work is primarily oriented around
  the education space.
show_excerpts: true

# Build settings
markdown: kramdown
remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Ryan Warsaw
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true
  social_links:
    github: ryanwarsaw
    linkedIn: in/ryanwarsaw
  analytics_id: UA-111542477-3
